### ISSUE TITLE
I have theater mode off but the video is still in theater mode

### ISSUE THREAD

**Issue by junchao-1837136** [sameernyaupane/simple-auto-hd#2]
I have to turn on and off again manually each time after I open a video to fix it.

**Comment by sameernyaupane** [comment]
First of all thanks for the query, Junchao.
You should toggle the theater mode from the extension popup itself. Doing it through YouTube will only be temporary. This is because the extension keeps its own cookie for the setting and does not regard YouTube's. This could be changed but if YouTube changes it's cookie variable name, it will cause breakage in extension. This is why I've hesitated to rely on it.

**Comment by sameernyaupane** [comment]
Finally I've added dual theater mode toggle to address this issue. Now it works with both Youtube's default toggle and through the popup as well. So the setting will sync between them. Will add it to v2.0.5 release.
